# LaTeX formatting configuration
# Limit line length to 100 characters

defaultIndent: '  '

# Enable text wrapping
modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1

  textWrapOptions:
    columns: 100
    when: after
    multipleSpacesToSingle: 1
    removeBlockLineBreaks: 0

  # Enable wrapping for all text
  paragraphsStopAt:
    environments: 0
    commands: 0
    ifElseFi: 0
    items: 0
    specialBeginEnd: 0
    heading: 0
    filecontents: 0

  paragraph:
    TextWrap: 2

  # Enable wrapping in environments
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    abstract:
      TextWrap: 2
    itemize:
      TextWrap: 2
    enumerate:
      TextWrap: 2

  # Wrap items in lists
  items:
    ItemStartsOnOwnLine: 1
    ItemFinishesWithLineBreak: 1
    TextWrap: 2
